# Postscript functions and configuration for the star design.
# -------------------------------------------------------
# This file is part of Embroidermodder.
# Copyright 2013-2022 The Embroidermodder Team
# See LICENSE for details.
# -------------------------------------------------------
#


star: |
    # The Star geometric primative class definition.
    def __init__(self):
        clearSelection()
        self.numPoints = 5
        self.modes = [\"NUM_POINTS\", \"CENTER_PT\", \"RAD_OUTER\", \"RAD_INNER\"]
        self.cx = nan
        self.cy = nan
        self.x1 = nan
        self.y1 = nan
        self.x2 = nan
        self.y2 = nan
        self.mode = \"NUM_POINTS\"
        prefix = translate(\"Enter number of star points\")
        prefix += \" \" + str(self.numPoints) + \"}: \"
        set_prompt_prefix(prefix)
    
    def click(self, x, y):
    if self.mode == \"NUM_POINTS\":
        #Do nothing, the prompt controls this.
        debug_message(\"do nothing\")
    elif self.mode == \"CENTER_PT\":
        self.cx = x
        self.cy = y
        self.mode = self.mode_RAD_OUTER
        set_prompt_prefix(translate(\"Specify outer radius of star: \"))
        addRubber(\"POLYGON\")
        setRubberMode(\"POLYGON\")
        updateStar(self.cx, self.cy)
        enableMoveRapidFire()
    elif self.mode == self.mode_RAD_OUTER:
        self.x1 = x
        self.y1 = y
        self.mode = self.mode_RAD_INNER
        set_prompt_prefix(translate(\"Specify inner radius of star: \"))
        updateStar(self.x1, self.y1)
    elif self.mode == self.mode_RAD_INNER:
        self.x2 = x
        self.y2 = y
        disableMoveRapidFire()
        updateStar(self.x2, self.y2)
        spareRubber(\"POLYGON\")
    
    def prompt(self, cmd):
    if self.mode == \"NUM_POINTS\":
        if str == \"\" and self.numPoints >= 3 and self.numPoints <= 1024:
            set_prompt_prefix(translate(\"Specify center point: \"))
            self.mode = self.mode_CENTER_PT
        else:
            tmp = int(cmd)
            if isnan(tmp) or not isinstance(tmp, int) or tmp < 3 or tmp > 1024:
                alert(translate(\"Requires an integer between 3 and 1024.\"))
                set_prompt_prefix(translate(\"Enter number of star points\")
                    + \" \" + self.numPoints.toString() + \"}: \")
            else:
                self.numPoints = tmp
                set_prompt_prefix(translate(\"Specify center point: \"))
                self.mode = \"CENTER_PT\"
    
    elif self.mode == \"CENTER_PT\":
        strList = str.split(\",\")
        if isNaN(strList[0]) or isNaN(strList[1]):
            alert(translate(\"Invalid point.\"))
            set_prompt_prefix(translate(\"Specify center point: \"))
        else:
            self.cx = float(strList[0])
            self.cy = float(strList[1])
            self.mode = \"RAD_OUTER\"
            set_prompt_prefix(translate(\"Specify outer radius of star: \"))
            updateStar(qsnapX(), qsnapY())
            enableMoveRapidFire()
    
    elif self.mode == \"RAD_OUTER\":
        strList = str.split(\",\")
        if isNaN(strList[0]) or isNaN(strList[1]):
            alert(translate(\"Invalid point.\"))
            set_prompt_prefix(translate(\"Specify outer radius of star: \"))
        else:
            self.x1 = float(strList[0])
            self.y1 = float(strList[1])
            self.mode = self.mode_RAD_INNER
            set_prompt_prefix(translate(\"Specify inner radius of star: \"))
            updateStar(qsnapX(), qsnapY())
    
    elif self.mode == self.mode_RAD_INNER:
        strList = str.split(
    )
        if isNaN(strList[0]) or isNaN(strList[1]):
            alert(translate(\"Invalid point.\"))
            set_prompt_prefix(translate(\"Specify inner radius of star: \"))
        else:
            self.x2 = float(strList[0])
            self.y2 = float(strList[1])
            disableMoveRapidFire()
            updateStar(self.x2, self.y2)
            spareRubber(\"POLYGON\")
    
    def update(self, x, y):
    distOuter
    distInner
    angOuter
    
    if self.mode == self.mode_RAD_OUTER:
        angOuter = calculateAngle(self.cx, self.cy, x, y)
        distOuter = calculateDistance(self.cx, self.cy, x, y)
        distInner = distOuter/2.0
    elif self.mode == self.mode_RAD_INNER:
        angOuter = calculateAngle(self.cx, self.cy, self.x1, self.y1)
        distOuter = calculateDistance(self.cx, self.cy, self.x1, self.y1)
        distInner = calculateDistance(self.cx, self.cy, x, y)
    
    #Calculate the Star Points
    angInc = 360.0/(self.numPoints*2)
    for i in range(self.numPoints*2):
        # if odd
        if i%2 == 1:
            xx = distOuter*cos((angOuter+(angInc*i))*pi/180.0)
            yy = distOuter*sin((angOuter+(angInc*i))*pi/180.0)
        else:
            xx = distInner*cos((angOuter+(angInc*i))*pi/180.0)
            yy = distInner*sin((angOuter+(angInc*i))*pi/180.0)
        setRubberPoint(\"POLYGON_POINT_\" + i.toString(), self.cx + xx, self.cy + yy)
    setRubberText(\"POLYGON_NUM_POINTS\", (self.numPoints*2 - 1).toString())
